name: Auto Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Run the workflow when there is a push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PI_SSH_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            cd ${{ secrets.PI_BACKEND_PROJECT_DIR_PATH }} &&
            git pull origin master &&
            ./restart_server.sh
          "
